### ISSUE TITLE
Simplifying software dependencies

### ISSUE THREAD

**Issue by leifdenby** [convml/convml_tt#14]
As @MarkUoLeeds mentioned by email it could be advantageous to split out software used for generating training data, training the model and doing interpretation. This could be achieved at least for pip-installable packages using "package extras", e.g.

```bash
$> pip install convml_tt[satellite_training_gen] convml_tt[rectpred]`
```
which for example could contain packages needed for generating training data based on GOES-16 (`satellite_training_gen`) or doing inference on Cartesian gridded data (`rectpred`) through applying the NN with a sliding window approach.

I need to work out wrt to splitting out requirements that are only installable with conda though for this be possible.

**Comment by leifdenby** [comment]
Another option would be to split data generation into a separate repository entirely. This could also make it easier to generalise training data creation.

**Comment by MarkUoLeeds** [comment]
> Another option would be to split data generation into a separate repository entirely. This could also make it easier to generalise training data creation.

I like this idea!

**Comment by leifdenby** [comment]
> I like this idea!

Ok, great! I'll have a think about how to do that

**Comment by leifdenby** [comment]
With the changes to move to pytorch-lightning I have also worked on this. Only the dependencies required for training and inference are now installed by default. Everything else is/will be in "extra requirements" [extras_require](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html?highlight=extras_require#optional-dependencies)
